### ISSUE TITLE
[BUG] Auto Close Popouts

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-common-display#64]
Currently does not auto close journals after the allotted time (user said it does still work on MEJ Pictures, haven't tried to replicate that).

https://github.com/ironmonk88/monks-common-display/assets/99844555/8f593190-a155-46a7-bb25-ad13fbbd2df2

Foundry 11.315
Common Display 11.07

**Comment by CaosFR** [comment]
Same for me, it's hard to stream and remerber to close each time.

Any hope for a fix soon ?

I have this error may it's help :

```
foundry.js:655 Error: Failed to render WebGL canvas. Cannot read properties of undefined (reading 'control')
[Detected 1 package: monks-common-display(12.01)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at Game.initializeCanvas (foundry.js:9274:13)
    at async Game.setupGame (foundry.js:9095:5)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)Caused by: TypeError: Cannot read properties of undefined (reading 'control')
[Detected 1 package: monks-common-display(12.01)]
    at MonksCommonDisplay.changeFocus (monks-common-display.js:529:31)
    at 🎁Scene.prototype.view#monks-common-display (monks-common-display.js:225:44)
    at async Game.initializeCanvas (foundry.js:9271:20)
    at async Game.setupGame (foundry.js:9095:5)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
```
